  DROP TABLE IF EXISTS users;
  CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
  );

  DROP TABLE IF EXISTS events;
  CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_name TEXT NOT NULL,
  event_date TEXT NOT NULL,
  event_time TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  city TEXT NOT NULL,
  price TEXT NOT NULL,
  graphic TEXT NOT NULL,
  category TEXT NOT NULL
  );

INSERT INTO events (event_name, event_date, event_time, description, location, city, price, graphic, category) VALUES
('Alanis Morissette', '12/11/2025', '20:30', 'Alanis Morissette is a Canadian-American singer, songwriter, and actress, born on June 1, 1974, in Ottawa, Ontario, Canada. She gained global recognition with her breakthrough album "Jagged Little Pill" in 1995, which sold over 33 million copies worldwide and won four Grammy Awards, including Album of the Year. Known for her emotive mezzo-soprano voice and confessional lyrics, Alanis has released several successful albums, including "Supposed Former Infatuation Junkie" in 1998 and "Flavors of Entanglement" in 2008. With over 75 million records sold globally, she continues to be a prominent figure in the music industry.', 'SEC armadillo, Glasgow', 'Glasgow', '50', 'images/alanis.png', 'music'),
('Clairo', '20/11/2025', '19:00', 'Clairo, born Claire Elizabeth Cottrill on August 18, 1998, is an American singer-songwriter from Atlanta, Georgia. She began sharing her music online at the age of 13 and gained widespread recognition in 2017 with the viral success of her lo-fi single "Pretty Girl." Since then, Clairo has released several successful albums, including her debut studio album "Immunity" (2019) and her second album "Sling" (2021). Known for her soft, intimate vocals and indie pop sound, Clairo continues to captivate audiences with her heartfelt music.', 'SSE Hydro, Glasgow', 'Glasgow', '45', 'images/clairo.jpg', 'music'),
('Coldplay', '29/09/2025', '21:00', 'Coldplay is a British rock band formed in London in 1996. The band consists of lead vocalist and pianist Chris Martin, lead guitarist Jonny Buckland, bassist Guy Berryman, and drummer Will Champion. They achieved worldwide fame with the release of their breakthrough single "Yellow" in 2000, followed by their debut album "Parachutes." Known for their melodic sound and introspective lyrics, Coldplay has released several critically acclaimed albums, including "A Rush of Blood to the Head" (2002) and "Viva la Vida or Death and All His Friends" (2008). With numerous awards, including seven Grammy Awards, and over 100 million albums sold worldwide, Coldplay continues to be a dominant force in the music industry.', 'O2 Academy, Glasgow', 'Glasgow', '60', 'images/coldplay.jpg', 'music'),
('The Eagles', '14/08/2025', '20:30', 'The Eagles are an American rock band formed in Los Angeles in 1971. The original lineup included Glenn Frey, Don Henley, Bernie Leadon, and Randy Meisner. Known for their country rock sound, The Eagles achieved immense success with hits like "Hotel California," "Take It Easy," and "Desperado." Their album "Hotel California" (1976) is one of the best-selling albums of all time. Throughout their career, they have won numerous awards, including six Grammy Awards, and have sold over 150 million records worldwide. The Eagles have been inducted into the Rock and Roll Hall of Fame and continue to be celebrated for their timeless music and influential contributions to rock and country music.', 'O2 Academy, Edinburgh', 'Edinburgh', '50', 'images/eagles.jpg', 'music'),
('Cage the Elephant', '10/12/2025', '19:30', 'Cage the Elephant is an American rock band formed in 2006 in Bowling Green, Kentucky. The band consists of vocalist Matt Shultz, guitarist Brad Shultz, drummer Jared Champion, and bassist Daniel Tichenor. Known for their energetic performances and eclectic sound that blends rock, alternative, and punk influences, Cage the Elephant gained significant attention with their self-titled debut album in 2008, featuring the hit single "Aint No Rest for the Wicked." Their subsequent albums, including "Thank You, Happy Birthday" (2011), "Melophobia" (2013), and "Social Cues" (2019), have cemented their place in the alternative rock scene. The band has won several awards, including a Grammy Award for Best Rock Album for "Tell Me Im Pretty" (2015), and they continue to captivate audiences with their dynamic music and live shows.', 'O2 Academy, Edinburgh', 'Edinburgh', '35', 'images/cage.jpg', 'music'),
('Darius Rucker', '13/08/2025', '18:00', 'Darius Rucker is an American singer and songwriter, born on May 13, 1966, in Charleston, South Carolina. He first gained fame as the lead vocalist and rhythm guitarist of the rock band Hootie & the Blowfish, which he founded in 1986. The band achieved massive success with their debut album "Cracked Rear View" (1994), which remains one of the best-selling albums of all time. In 2008, Rucker embarked on a successful solo career in country music, releasing his debut country album "Learn to Live," which produced three number-one hits. Known for his distinctive voice and crossover appeal, Darius Rucker has received numerous awards, including multiple Country Music Association Awards and Grammy Awards. He continues to be a prominent figure in both rock and country music.', 'O2 Academy, Edinburgh', 'Edinburgh', '40', 'images/Darius.jpg', 'music'),
('Daft Punk', '03/11/2025', '20:00', 'Daft Punk is a French electronic music duo formed in 1993 by musicians Guy-Manuel de Homem-Christo and Thomas Bangalter. They are celebrated for their pioneering influence on the electronic music scene, blending elements of house, funk, disco, rock, and pop to create a distinctive sound. The duo is known for their innovative approach to music and performance, often performing with elaborate helmets and costumes that maintain their anonymity.  Daft Punks debut album, "Homework," released in 1997, featured iconic tracks like "Around the World" and "Da Funk," which helped establish them as major figures in the music industry. Their second album, "Discovery," released in 2001, included hits such as "One More Time" and "Harder, Better, Faster, Stronger," further cementing their status as electronic music legends.', 'SEC Armadillo, Glasgow', 'Glasgow', '45', 'images/daftpunk.jpg', 'music'),
('Lang Lang', '27/10/2025', '17:30', 'Lang Lang is a Chinese pianist born on June 14, 1982, in Shenyang, Liaoning, China. He is widely regarded as one of the most prominent and exciting pianists of his generation. Lang Lang began playing the piano at the age of three and quickly gained recognition for his exceptional talent. He has performed with leading orchestras around the world, including the Berlin Philharmonic, the Vienna Philharmonic, and the New York Philharmonic. Known for his passionate and virtuosic performances, Lang Lang has also been an influential ambassador for classical music, bringing it to new audiences through his numerous television appearances, recordings, and educational initiatives. His expressive playing and charismatic stage presence have made him a beloved figure in the world of classical music.', 'Usher Hall, Edinburgh', 'Edinburgh', '40', 'images/langlang.jpg', 'music'),
('Pantera', '02/12/2025', '19:30', 'Pantera is an American heavy metal band formed in Arlington, Texas, in 1981 by the Abbott brothers, guitarist Dimebag Darrell and drummer Vinnie Paul. The bands lineup solidified with the addition of bassist Rex Brown and vocalist Phil Anselmo in the late 1980s. Pantera is renowned for pioneering the groove metal subgenre and achieving mainstream success with their 1990 album "Cowboys from Hell." Their aggressive style, powerful riffs, and intense performances earned them a dedicated fanbase. Some of their most notable albums include "Vulgar Display of Power" (1992) and "Far Beyond Driven" (1994), the latter of which debuted at number one on the Billboard 200 chart. Despite disbanding in 2003, Panteras influence on the metal genre remains significant, and they are remembered as one of the most important bands in heavy metal history.', 'OVO Hydro, Glasgow', 'Glasgow', '35', 'images/pantera.jpg', 'music'),
('Ricky Gervais', '15/10/2025', '18:30', 'Ricky Gervais is an English comedian, actor, writer, director, and musician, born on June 25, 1961, in Reading, Berkshire, England. He is best known for co-creating, co-writing, and acting in the British television sitcoms The Office (2001-2003), Extras (2005-2007), and Lifes Too Short (2011-2013). Ricky also created, wrote, and starred in Derek (2012-2014) and After Life (2019-2022).  Before his successful career in comedy, Ricky attempted a pop career in the 1980s as part of the new-wave duo Seona Dancing. He later transitioned to comedy and has since won numerous awards, including seven BAFTA Awards, five British Comedy Awards, two Emmy Awards, and four Golden Globe Awards.', 'O2 Academy, Edinburgh', 'Edinburgh', '60', 'images/rickyg.jpg', 'comedy'),
('Peter Kay', '13/11/2025', '20:00', 'Peter Kay is an English comedian, actor, writer, and director, born on July 2, 1973, in Farnworth, Lancashire, England. He is best known for his work on television shows such as That Peter Kay Thing, Phoenix Nights, Max and Paddys Road to Nowhere, and Peter Kays Car Share. Peter Kay has also made a name for himself in the world of stand-up comedy, winning numerous awards and accolades for his performances.  Before his successful career in comedy, Peter studied media performance at the University of Salford. He began working part-time as a stand-up comedian and quickly rose to fame, winning the North West Comedian of the Year award and Channel 4s So You Think Youre Funny contest. His comedic talent has earned him several BAFTA Awards, British Comedy Awards, and an honorary doctorate from the University of Salford.', 'O2 Academy, Glasgow', 'Glasgow', '55', 'images/peterk.jpg', 'comedy'),
('Paul Smith', '26/10/2025', '16:30', 'Paul Smith is a British comedian, born on July 2, 1973, in Farnworth, Lancashire, England. He is best known for his quick wit and affable nature, which have made him a favorite at comedy clubs across the UK. Paul began his comedy career in 2006 after taking a four-week stand-up comedy course to overcome his shyness. He has won several awards, including Liverpools New Comedian of the Year and being a finalist at The Leicester Comedian of the Year competition.  Pauls rise to fame was significantly boosted by his online presence, with viral clips of his performances attracting a large following. His unique style of roasting audience members has made him a standout performer, and he has since headlined numerous tours, including his latest show "Pablo." Paul continues to entertain audiences with his hilarious true stories and audience interactions, making him one of the most popular comedians in the UK.', 'SEC Armadillo, Glasgow', 'Glasgow', '50', 'images/pauls.png', 'comedy'),
('Bill Burr', '04/11/2025', '19:00', 'Bill Burr is an American stand-up comedian, actor, writer, and podcaster, born on June 10, 1968, in Canton, Massachusetts. Known for his observational comedy, black comedy, and satirical style, Burr has become one of the most respected comedians of his generation.  He began his comedy career in 1992 and quickly gained recognition with appearances on television shows and in films. Burr is also well-known for creating and voicing the lead character in the animated sitcom "F Is for Family."  In addition to his stand-up specials, such as "Paper Tiger" and "Im Sorry You Feel That Way," Burr hosts the popular "Monday Morning Podcast" and co-founded the All Things Comedy network. His sharp wit and candid humor have earned him a loyal fan base and numerous accolades, including a Primetime Emmy Award nomination and a Grammy Award nomination.', 'The Playhouse, Edinburgh', 'Edinburgh', '35', 'images/billb.jpg', 'comedy'),
('Kevin Hart', '29/12/2025', '20:00', 'Kevin Hart is an American comedian, actor, and producer, born on July 6, 1979, in Philadelphia, Pennsylvania. Known for his energetic performances and quick wit, Hart has become one of the most popular comedians in the world. He began his comedy career in 2000 and gained national recognition after releasing his first stand-up special, "Im a Grown Little Man," in 2009.  Hart has starred in numerous films, including "Jumanji: Welcome to the Jungle," "Night School," and "The Secret Life of Pets" series. He is also known for his role as a producer and host of the game show "Jeopardy!" and for his popular stand-up specials like "Laugh at My Pain" and "What Now?".  In addition to his work in comedy and film, Hart is a successful entrepreneur, having launched his own production company, HartBeat Productions, and a line of tequila. He continues to be a prominent figure in the entertainment industry, known for his humor, charisma, and dedication to his craft.', 'O2 Academy, Edinburgh', 'Edinburgh', '35', 'images/kevinb.jpg', 'comedy'),
('Kevin Bridges', '08/10/2025', '18:30', 'Kevin Bridges is a Scottish stand-up comedian, born on November 13, 1986, in Clydebank, West Dunbartonshire. He began his comedy career at the young age of 17 and quickly rose to fame with his sharp observational humor and relatable storytelling. Bridges gained national recognition after reaching the final of the "So You Think Youre Funny" competition at the Edinburgh Fringe Festival.  He has since performed at major comedy festivals and venues, including the Edinburgh Festival Fringe and Michael McIntyres Comedy Roadshow. Bridges has released several successful stand-up DVDs, such as "Kevin Bridges: The Story So Far..." and "Kevin Bridges: A Whole Different Story," which have sold hundreds of thousands of copies.  In addition to his stand-up career, Bridges has appeared on numerous television shows, showcasing his comedic talent. He is also known for his role as a host and producer of various comedy programs.', 'O2 Academy, Glasgow', 'Glasgow', '35', 'images/kevinh.jpg', 'comedy'),
('Jimmy Carr', '14/09/2025', '19:30', 'Jimmy Carr is a British-Irish comedian, writer, and television host, born on September 15, 1972, in Isleworth, London, England. Known for his rapid-fire delivery and dark humor, Jimmy has become one of the UKs most successful comedians. He began his comedy career in 1997 after leaving a career in marketing and quickly gained recognition for his sharp wit and distinctive style.  Over the years, Jimmy has appeared on numerous television shows, including 8 Out of 10 Cats, Roast Battle, and The Fix. His work on these shows, combined with his stand-up tours, has solidified his reputation as a top comedian. Jimmys comedy is characterized by its dark humor, one-liners, and quick comebacks, making him a unique figure in the comedy world. He continues to perform to sold-out audiences around the world.', 'The Playhouse, Edinburgh', 'Edinburgh', '60', 'images/jimmyc.jpg', 'comedy'),
('Maisie Adam', '15/12/2025', '21:00', 'Maisie Adam is a British comedian, writer, and actress, born on January 24, 1994, in Pannal, North Yorkshire, England. She is known for her witty and energetic performances, which have made her a rising star in the comedy world. Maisie began her career in stand-up comedy in 2016 after facing challenges in securing acting jobs. Her debut came at the Ilkley Literature Festival fringe, and she quickly gained recognition by winning the "So You Think Youre Funny" contest at the Edinburgh Fringe Festival in 2017. Since then, she has appeared on various television shows, including 8 Out of 10 Cats, Mock the Week, and QI. Maisie continues to entertain audiences with her unique style and humor.', 'OVO Hydro, Glasgow', 'Glasgow', '40', 'images/maisie.jpg', 'comedy'),
('Aurie Styla', '03/09/2025', '18:00', 'Aurie Styla is a British comedian, actor, and writer, born on November 29, 1987, in England. He is known for his unique style and infectious humor, which have made him a standout performer in the UK comedy scene. Aurie began his comedy career in 2010 and quickly gained recognition for his sharp wit and engaging stage presence.  Over the years, Aurie has appeared on various television shows, showcasing his versatility and talent. He is also a popular radio personality, known for his appearances on shows like The Now Show and NewsJack on BBC Radio 4. In addition to his work on stage and screen, Aurie has hosted numerous live events and comedy nights, earning a loyal fan base with his relatable and charismatic performances.', 'The Playhouse, Edinburgh', 'Edinburgh', '35', 'images/aurie.jpg', 'comedy');


  DROP TABLE IF EXISTS local;
  CREATE TABLE local (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  bio TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  socialmedia NOT NULL
  );

  INSERT INTO local (name, bio, email, phone, socialmedia) VALUES
    ('Jack Campbell', 'I am a singer-songwriter from Edinburgh with a passion for acoustic performances.  I would like to play at gigs anywhere around the city, please get in touch if you would like me to send any of my songs or book me for a gig.', 'jackcampbell321@gmail.com', '07976398473', 'https://en-gb.facebook.com/'),
    ('Callum Frazer', 'My name is Callum, I am an up and coming comedian from Aberdeen who loves a good laugh.  My comedy is a mix of Scottish banter and everyday life, I manage to find the funny side of most things in life.  I look forward to hearing from you.', 'callumfraser3@gmail.co.uk', '07730925638', 'https://en-gb.facebook.com/'),
    ('Emily McKenzie', 'Hi, I am Emily, a folk singer from Inverness.  My music is inspired through stories passed down through generations.  I love creating songs that connect people to their roots, please send me an email fo find out more.', 'emilyfolkartist@icloud.com', '07828497624', 'https://www.instagram.com/'),
    ('Jamie Anthony', 'Hiya, I am Jamie, a fresh face on the Edinburgh comedy scene.  I enjoy making folk laugh with life stories and sharp wit.  I am just starting out but if you are up for a laugh, I am your guy', 'laughjkenny@hotmail.co.uk', '07990826567', 'https://www.instagram.com/'),
    ('Jade Robertson', 'I see my voice as my instrument and I love exploring different styles of music.  Whether it is a small local gig or just playing for a few friends, my goal is to always connect with the audience through music.', 'roberstonmusic@mail.co.uk', '07961214276', 'https://www.instagram.com/'),
    ('The Rock Crew', 'We are a rock band based in Glasgow, fresh on the scene but never fail to bring the energy.  We are all willing to travel to other towns or cities to perform so do not hesitate to reach out!.', 'therockcrew@hotmail.co.uk', '07123189567', 'https://en-gb.facebook.com/');
