   DROP TABLE IF EXISTS events;
  CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_name TEXT NOT NULL,
  event_date TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL,
  city TEXT NOT NULL,
  price TEXT NOT NULL,
  graphic TEXT NOT NULL,
  category TEXT NOT NULL
  );

INSERT INTO events (event_name, event_date, description, location, city, price, graphic, category) VALUES
('Alanis Morissette', '12/11/2025', 'Alanis Morissette is a Canadian-American singer, songwriter, and actress, born on June 1, 1974, in Ottawa, Ontario, Canada. She gained global recognition with her breakthrough album "Jagged Little Pill" in 1995, which sold over 33 million copies worldwide and won four Grammy Awards, including Album of the Year. Known for her emotive mezzo-soprano voice and confessional lyrics, Alanis has released several successful albums, including "Supposed Former Infatuation Junkie" in 1998 and "Flavors of Entanglement" in 2008. With over 75 million records sold globally, she continues to be a prominent figure in the music industry.', 'EH417HG', 'Edinburgh', '50', 'images/alanis.png', 'music'),
('Clairo', '20/11/2025', 'Clairo, born Claire Elizabeth Cottrill on August 18, 1998, is an American singer-songwriter from Atlanta, Georgia. She began sharing her music online at the age of 13 and gained widespread recognition in 2017 with the viral success of her lo-fi single "Pretty Girl." Since then, Clairo has released several successful albums, including her debut studio album "Immunity" (2019) and her second album "Sling" (2021). Known for her soft, intimate vocals and indie pop sound, Clairo continues to captivate audiences with her heartfelt music.', 'EH417HG', 'Glasgow', '45', 'images/clairo.jpg', 'music'),
('Coldplay', '29/09/2025', 'Coldplay is a British rock band formed in London in 1996. The band consists of lead vocalist and pianist Chris Martin, lead guitarist Jonny Buckland, bassist Guy Berryman, and drummer Will Champion. They achieved worldwide fame with the release of their breakthrough single "Yellow" in 2000, followed by their debut album "Parachutes." Known for their melodic sound and introspective lyrics, Coldplay has released several critically acclaimed albums, including "A Rush of Blood to the Head" (2002) and "Viva la Vida or Death and All His Friends" (2008). With numerous awards, including seven Grammy Awards, and over 100 million albums sold worldwide, Coldplay continues to be a dominant force in the music industry.', 'EH417HG', 'Glasgow', '60', 'images/coldplay.jpg', 'music'),
('The Eagles', '14/08/2025', 'The Eagles are an American rock band formed in Los Angeles in 1971. The original lineup included Glenn Frey, Don Henley, Bernie Leadon, and Randy Meisner. Known for their country rock sound, The Eagles achieved immense success with hits like "Hotel California," "Take It Easy," and "Desperado." Their album "Hotel California" (1976) is one of the best-selling albums of all time. Throughout their career, they have won numerous awards, including six Grammy Awards, and have sold over 150 million records worldwide. The Eagles have been inducted into the Rock and Roll Hall of Fame and continue to be celebrated for their timeless music and influential contributions to rock and country music.', 'EH417HG', 'Edinburgh', '50', 'images/eagles.jpg', 'music'),
('Cage the Elephant', '10/12/2025', 'Cage the Elephant is an American rock band formed in 2006 in Bowling Green, Kentucky. The band consists of vocalist Matt Shultz, guitarist Brad Shultz, drummer Jared Champion, and bassist Daniel Tichenor. Known for their energetic performances and eclectic sound that blends rock, alternative, and punk influences, Cage the Elephant gained significant attention with their self-titled debut album in 2008, featuring the hit single "Aint No Rest for the Wicked." Their subsequent albums, including "Thank You, Happy Birthday" (2011), "Melophobia" (2013), and "Social Cues" (2019), have cemented their place in the alternative rock scene. The band has won several awards, including a Grammy Award for Best Rock Album for "Tell Me Im Pretty" (2015), and they continue to captivate audiences with their dynamic music and live shows.', 'EH417HG', 'Glasgow', '35', 'images/cage.jpg', 'music'),
('Darius Rucker', '13/08/2025', 'Darius Rucker is an American singer and songwriter, born on May 13, 1966, in Charleston, South Carolina. He first gained fame as the lead vocalist and rhythm guitarist of the rock band Hootie & the Blowfish, which he founded in 1986. The band achieved massive success with their debut album "Cracked Rear View" (1994), which remains one of the best-selling albums of all time. In 2008, Rucker embarked on a successful solo career in country music, releasing his debut country album "Learn to Live," which produced three number-one hits. Known for his distinctive voice and crossover appeal, Darius Rucker has received numerous awards, including multiple Country Music Association Awards and Grammy Awards. He continues to be a prominent figure in both rock and country music.', 'EH417HG', 'Edinburgh', '40', 'images/Darius.jpg', 'music'),
('Faithless', '03/11/2025', 'Faithless is a British electronic music group formed in 1995. The original lineup included Rollo Armstrong, Sister Bliss, and Maxi Jazz. They are known for their pioneering blend of house, trance, and trip-hop music. Faithless gained widespread acclaim with their debut album "Reverence" in 1996, which included hit singles like "Insomnia" and "Salva Mea." Over the years, they have released several successful albums, including "Sunday 8PM" (1998) and "No Roots" (2004), and their music has remained influential within the electronic dance music scene. With their evocative lyrics, powerful beats, and memorable live performances, Faithless has sold millions of records worldwide and continues to be celebrated for their innovative contributions to music.', 'Armadillo, Glasgow', 'Edinburgh', '45', 'images/faithless.jpg', 'music'),
('Lang Lang', '27/10/2025', 'Lang Lang is a Chinese pianist born on June 14, 1982, in Shenyang, Liaoning, China. He is widely regarded as one of the most prominent and exciting pianists of his generation. Lang Lang began playing the piano at the age of three and quickly gained recognition for his exceptional talent. He has performed with leading orchestras around the world, including the Berlin Philharmonic, the Vienna Philharmonic, and the New York Philharmonic. Known for his passionate and virtuosic performances, Lang Lang has also been an influential ambassador for classical music, bringing it to new audiences through his numerous television appearances, recordings, and educational initiatives. His expressive playing and charismatic stage presence have made him a beloved figure in the world of classical music.', 'O2, Glasgow', 'Glasgow', '40', 'images/langlang.jpg', 'music'),
('Pantera', '02/12/2025', 'Pantera was an American heavy metal band formed in Arlington, Texas, in 1981 by the Abbott brothers, guitarist Dimebag Darrell and drummer Vinnie Paul. The bands lineup solidified with the addition of bassist Rex Brown and vocalist Phil Anselmo in the late 1980s. Pantera is renowned for pioneering the groove metal subgenre and achieving mainstream success with their 1990 album "Cowboys from Hell." Their aggressive style, powerful riffs, and intense performances earned them a dedicated fanbase. Some of their most notable albums include "Vulgar Display of Power" (1992) and "Far Beyond Driven" (1994), the latter of which debuted at number one on the Billboard 200 chart. Despite disbanding in 2003, Panteras influence on the metal genre remains significant, and they are remembered as one of the most important bands in heavy metal history.', 'OVO Hydro, Glasgow', 'Edinburgh', '35', 'images/pantera.jpg', 'music');


 DROP TABLE IF EXISTS local;
  CREATE TABLE local (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  bio TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  socialmedia NOT NULL
  );

  INSERT INTO local (name, bio, email, phone, socialmedia) VALUES
    ('Jack Campbell', 'I am a singer-songwriter from Edinburgh with a passion for acoustic performances.  I would like to play at gigs anywhere around the city, please get in touch if you would like me to send any of my songs or book me for a gig.', 'jackcampbell321@gmail.com', '07976398473', 'https://en-gb.facebook.com/'),
    ('Callum Frazer', 'My name is Callum, I am an up and coming comedian from Aberdeen who loves a good laugh.  My comedy is a mix of Scottish banter and everyday life, I manage to find the funny side of most things in life.  I look forward to hearing from you.', 'callumfraser3@gmail.co.uk', '07730925638', 'https://en-gb.facebook.com/'),
    ('Emily McKenzie', 'Hi, I am Emily, a folk singer from Inverness.  My music is inspired through stories passed down through generations.  I love creating songs that connect people to their roots, please send me an email fo find out more.', 'emilyfolkartist@icloud.com', '07828497624', 'https://www.instagram.com/'),
    ('Jamie Anthony', 'Hiya, I am Jamie, a fresh face on the Edinburgh comedy scene.  I enjoy making folk laugh with life stories and sharp wit.  I am just starting out but if you are up for a laugh, I am your guy', 'laughjkenny@hotmail.co.uk', '07990826567', 'https://www.instagram.com/'),
    ('Jade Robertson', 'I see my voice as my instrument and I love exploring different styles of music.  Whether it is a small local gig or just playing for a few friends, my goal is to always connect with the audience through music.', 'roberstonmusic@mail.co.uk', '07961214276', 'https://www.instagram.com/'),
    ('The Rock Crew', 'We are a rock band based in Glasgow, fresh on the scene but never fail to bring the energy.  We are all willing to travel to other towns or cities to perform so do not hesitate to reach out!.', 'therockcrew@hotmail.co.uk', '07123189567', 'https://en-gb.facebook.com/');